// SPDX-FileCopyrightText: 2026 ChouChiu
// SPDX-License-Identifier: GPL-3.0-or-later

use std::collections::BTreeMap;
use std::process::Command;
use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());

    let dep_names = parse_cargo_toml_deps(&manifest_dir.join("Cargo.toml"));
    let versions = parse_cargo_lock_versions(&manifest_dir.join("Cargo.lock"), &dep_names);
    let licenses = licenses_from_metadata(&manifest_dir, &dep_names);

    let mut entries: Vec<String> = Vec::new();
    for name in &dep_names {
        let version = versions.get(name).map(String::as_str).unwrap_or("unknown");
        let license = licenses.get(name).map(String::as_str).unwrap_or("unknown");
        entries.push(format!("    (\"{name}\", \"{version}\", \"{license}\"),\n"));
    }

    let code = format!(
        "// Generated by build.rs — do not edit by hand.\n\
         pub(super) const DEPENDENCIES: &[(&str, &str, &str)] = &[\n{entries}];\n",
        entries = entries.concat(),
    );

    fs::write(out_dir.join("dep_list.rs"), code).expect("write dep_list.rs");

    println!("cargo::rerun-if-changed=Cargo.toml");
    println!("cargo::rerun-if-changed=Cargo.lock");
    println!("cargo::rerun-if-changed=build.rs");
}

/// Extracts dependency names from the `[dependencies]` section of Cargo.toml.
fn parse_cargo_toml_deps(path: &PathBuf) -> Vec<String> {
    let content = fs::read_to_string(path).expect("read Cargo.toml");

    let mut names = Vec::new();
    let mut in_deps = false;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == "[dependencies]" {
            in_deps = true;
            continue;
        }
        if in_deps {
            if trimmed.starts_with('[') || trimmed.is_empty() {
                break;
            }
            if let Some((key, value)) = trimmed.split_once('=') {
                let key = key.trim();
                // Handle renamed dependency: `gtk = { package = "gtk4", ... }`
                let pkg_name = if value.trim().starts_with('{') {
                    value
                        .split("package = \"")
                        .nth(1)
                        .and_then(|rest| rest.split('"').next())
                        .unwrap_or(key)
                } else {
                    key
                };
                if !pkg_name.is_empty() {
                    names.push(pkg_name.to_string());
                }
            }
        }
    }

    names
}

/// Reads Cargo.lock and returns resolved versions for the given dependency names.
fn parse_cargo_lock_versions(path: &PathBuf, wanted: &[String]) -> BTreeMap<String, String> {
    let content = fs::read_to_string(path).expect("read Cargo.lock");

    let mut versions = BTreeMap::new();
    let mut current_name = String::new();
    let mut in_package = false;

    for line in content.lines() {
        let trimmed = line.trim();
        match trimmed {
            "[[package]]" => {
                in_package = true;
                current_name.clear();
            }
            _ if trimmed.is_empty() => {
                in_package = false;
            }
            _ if in_package => {
                if let Some(value) = trimmed.strip_prefix("name = ") {
                    current_name = value.trim_matches('"').to_string();
                } else if let Some(value) = trimmed.strip_prefix("version = ")
                    && wanted.contains(&current_name)
                {
                    versions.insert(current_name.clone(), value.trim_matches('"').to_string());
                }
            }
            _ => {}
        }
    }

    versions
}

/// Runs `cargo metadata` and extracts license info for the given dependency names.
fn licenses_from_metadata(manifest_dir: &PathBuf, wanted: &[String]) -> BTreeMap<String, String> {
    let output = Command::new(env::var_os("CARGO").unwrap_or_else(|| "cargo".into()))
        .args(["metadata", "--format-version", "1"])
        .current_dir(manifest_dir)
        .output();

    let Ok(output) = output else {
        return BTreeMap::new();
    };
    if !output.status.success() {
        return BTreeMap::new();
    }

    let Ok(json) = serde_json::from_slice::<serde_json::Value>(&output.stdout) else {
        return BTreeMap::new();
    };

    let mut licenses: BTreeMap<String, String> = BTreeMap::new();
    let resolve = json.get("resolve").and_then(|v| v.as_object());
    let root_id = resolve.and_then(|r| r.get("root")).and_then(|v| v.as_str());

    // Find root node and collect direct dependency package ids.
    let mut direct_ids = Vec::new();
    if let Some(resolve) = resolve
        && let Some(nodes) = resolve.get("nodes").and_then(|v| v.as_array())
    {
        for node in nodes {
            if node.get("id").and_then(|v| v.as_str()) == root_id {
                if let Some(deps) = node.get("deps").and_then(|v| v.as_array()) {
                    for dep in deps {
                        if let Some(pkg) = dep.get("pkg").and_then(|v| v.as_str()) {
                            direct_ids.push(pkg.to_string());
                        }
                    }
                }
                break;
            }
        }
    }

    // Map package ids to names and licenses.
    if let Some(packages) = json.get("packages").and_then(|v| v.as_array()) {
        for pkg in packages {
            let Some(id) = pkg.get("id").and_then(|v| v.as_str()) else {
                continue;
            };
            if !direct_ids.iter().any(|did| did == id) {
                continue;
            }
            let Some(name) = pkg.get("name").and_then(|v| v.as_str()) else {
                continue;
            };
            if !wanted.contains(&name.to_string()) {
                continue;
            }
            let license = pkg
                .get("license")
                .and_then(|v| v.as_str())
                .unwrap_or("unknown");
            licenses.insert(name.to_string(), license.to_string());
        }
    }

    licenses
}
