// SPDX-FileCopyrightText: 2026 ChouChiu
// SPDX-License-Identifier: GPL-3.0-or-later

use std::collections::BTreeMap;
use std::process::Command;
use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());

    let dep_names = parse_cargo_toml_deps(&manifest_dir.join("Cargo.toml"));
    let packages = packages_from_metadata(&manifest_dir, &dep_names);

    let mut entries: Vec<String> = Vec::new();
    for name in &dep_names {
        let (version, license) = packages
            .get(name)
            .map(|(version, license)| (version.as_str(), license.as_str()))
            .unwrap_or(("unknown", "unknown"));
        entries.push(format!("    (\"{name}\", \"{version}\", \"{license}\"),\n"));
    }

    let code = format!(
        "// Generated by build.rs — do not edit by hand.\n\
         pub(super) const DEPENDENCIES: &[(&str, &str, &str)] = &[\n{entries}];\n",
        entries = entries.concat(),
    );

    fs::write(out_dir.join("dep_list.rs"), code).expect("write dep_list.rs");

    println!("cargo::rerun-if-changed=Cargo.toml");
    println!("cargo::rerun-if-changed=Cargo.lock");
    println!("cargo::rerun-if-changed=build.rs");
}

/// Extracts package names from the `[dependencies]` table of Cargo.toml.
fn parse_cargo_toml_deps(path: &PathBuf) -> Vec<String> {
    let content = fs::read_to_string(path).expect("read Cargo.toml");
    let manifest: toml::Value = toml::from_str(&content).expect("parse Cargo.toml");
    let dependencies = manifest
        .get("dependencies")
        .and_then(toml::Value::as_table)
        .expect("Cargo.toml [dependencies] table");

    dependencies
        .iter()
        .map(|(alias, specification)| {
            specification
                .as_table()
                .and_then(|table| table.get("package"))
                .and_then(toml::Value::as_str)
                .unwrap_or(alias)
                .to_string()
        })
        .collect()
}

/// Runs `cargo metadata` and extracts exact versions and licenses for direct dependencies.
fn packages_from_metadata(
    manifest_dir: &PathBuf,
    wanted: &[String],
) -> BTreeMap<String, (String, String)> {
    let output = Command::new(env::var_os("CARGO").unwrap_or_else(|| "cargo".into()))
        .args(["metadata", "--format-version", "1", "--locked"])
        .current_dir(manifest_dir)
        .output();

    let Ok(output) = output else {
        return BTreeMap::new();
    };
    if !output.status.success() {
        return BTreeMap::new();
    }

    let Ok(json) = serde_json::from_slice::<serde_json::Value>(&output.stdout) else {
        return BTreeMap::new();
    };

    let mut packages_by_name = BTreeMap::new();
    let resolve = json.get("resolve").and_then(|v| v.as_object());
    let root_id = resolve.and_then(|r| r.get("root")).and_then(|v| v.as_str());

    // Find root node and collect direct dependency package ids.
    let mut direct_ids = Vec::new();
    if let Some(resolve) = resolve
        && let Some(nodes) = resolve.get("nodes").and_then(|v| v.as_array())
    {
        for node in nodes {
            if node.get("id").and_then(|v| v.as_str()) == root_id {
                if let Some(deps) = node.get("deps").and_then(|v| v.as_array()) {
                    for dep in deps {
                        if let Some(pkg) = dep.get("pkg").and_then(|v| v.as_str()) {
                            direct_ids.push(pkg.to_string());
                        }
                    }
                }
                break;
            }
        }
    }

    // Map package ids to names and licenses.
    if let Some(packages) = json.get("packages").and_then(|v| v.as_array()) {
        for pkg in packages {
            let Some(id) = pkg.get("id").and_then(|v| v.as_str()) else {
                continue;
            };
            if !direct_ids.iter().any(|did| did == id) {
                continue;
            }
            let Some(name) = pkg.get("name").and_then(|v| v.as_str()) else {
                continue;
            };
            if !wanted.contains(&name.to_string()) {
                continue;
            }
            let version = pkg
                .get("version")
                .and_then(|v| v.as_str())
                .unwrap_or("unknown");
            let license = pkg
                .get("license")
                .and_then(|v| v.as_str())
                .unwrap_or("unknown");
            packages_by_name.insert(name.to_string(), (version.to_string(), license.to_string()));
        }
    }

    packages_by_name
}
