# SPDX-FileCopyrightText: 2026 ChouChiu
# SPDX-License-Identifier: AGPL-3.0-only

[build]
rustdocflags = ["-D", "warnings"]

[alias]
docs = "doc --locked --workspace --no-deps --document-private-items"
docs-open = "doc --locked --workspace --no-deps --document-private-items --open"
